### ISSUE TITLE
Any plans to push the source code? Really looking forward to it.

### ISSUE THREAD

**Issue by RahulBhalley** [rosinality/nansy-pytorch#1]

**Comment by rosinality** [comment]
I am currently implementing this. 😅 I will take some time for implementation and experiments.

**Comment by RahulBhalley** [comment]
Sure, no issues. :) It would really help me also implement it on my end if you could please share some references repositories that you're probably looking at right now to implement NANSY. 

Regards
Rahul Bhalley

**Comment by rosinality** [comment]
Hmm, I'm currently trying to implement it from the paper. librosa/torchaudio/parselmouth was helpful.

**Comment by RahulBhalley** [comment]
Ok, thanks!

**Comment by RahulBhalley** [comment]
Hi @rosinality any updates on this?

**Comment by rosinality** [comment]
I have almost implemented the model, but I found aligning features which have different sampling ratios/window sizes (wav2vec features vs mel, yingram features) is not straightforward. Currently I am stopped at that point.

**Comment by RahulBhalley** [comment]
Ok, thanks for updating me. :)
